syntax = "proto3";

option java_package = "emu.grasscutter.net.proto";
option java_outer_classname = "_FilmfestBallGameActionOuterClass";

import "_Vector2Int.proto";

message _FilmfestBallGameAction {
	enum _FilmfestBallGameActionType {
		ACTION_TYPE_NONE = 0;
		ACTION_TYPE_PLAYER_MOVE = 1;
		ACTION_TYPE_SPAWN_WAVE = 2;
		ACTION_TYPE_ADD_OBSTACLE = 3;
		ACTION_TYPE_REMOVE_OBSTACLE = 4;
		ACTION_TYPE_TEAM_SCORE = 5;
		ACTION_TYPE_COLLECT_OBSTACLES = 6;
		ACTION_TYPE_CHANGE_STAGE = 7;
		ACTION_TYPE_CREATE_COLOR_ZONE = 8;
		ACTION_TYPE_ADD_RIGHT_PUSH_COUNT = 9;
	}
	_FilmfestBallGameActionType action_type = 1;
	uint64 client_game_time = 2;
	uint64 server_game_time = 3;
	bool is_failed = 4;
	_Vector2Int pos = 5;
	uint32 peer_id = 6;
	uint64 execution_game_time = 7;
	_Vector2Int dir = 8;
	int32 rot = 9;
	repeated uint32 entity_id_list = 10;
	uint32 EKNOCDAOCOO = 11;
	bool PEHLOIBOPLP = 12;
	int32 radius = 13;
}
