syntax = "proto3";

option java_package = "emu.grasscutter.net.proto";
option java_outer_classname = "AbilityMetaModifierChangeOuterClass";

import "AbilityAttachedModifier.proto";
import "AbilityString.proto";
import "ModifierAction.proto";
import "ModifierProperty.proto";

message AbilityMetaModifierChange {
	repeated ModifierProperty properties = 1;
	AbilityString parent_ability_name = 2;
	bool NBBGHMGOALL = 3;
	bool is_attached_parent_ability = 4;
	uint64 OCAMKBCONED = 5;
	AbilityString parent_ability_override = 6;
	float MFBDIICANOF = 9;
	uint32 apply_entity_id = 10;
	ModifierAction action = 11;
	uint32 server_buff_uid = 12;
	int32 modifier_local_id = 13;
	AbilityAttachedModifier attached_instanced_modifier = 14;
	bool PKJMOLPCEBG = 15;
}
