syntax = "proto3";

option java_package = "emu.grasscutter.net.proto";
option java_outer_classname = "AbilityInvokeEntryOuterClass";

import "AbilityInvokeArgument.proto";
import "AbilityInvokeEntryHead.proto";
import "ForwardType.proto";

message AbilityInvokeEntry {
	uint32 event_id = 1;
	double total_tick_time = 5;
	AbilityInvokeEntryHead head = 6;
	bool is_ignore_auth = 7;
	bytes ability_data = 8;
	AbilityInvokeArgument argument_type = 9;
	uint32 entity_id = 10;
	ForwardType forward_type = 12;
	uint32 forward_peer = 15;
}
