syntax = "proto3";

option java_package = "emu.grasscutter.net.proto";
option java_outer_classname = "ActivityInfoOuterClass";

import "AcrobaticsBattleDetailInfo.proto";
import "ActivityMultiCharacterDetailInfo.proto";
import "ActivityPushTipsData.proto";
import "ActivityWatcherInfo.proto";
import "AdShootingDetailInfo.proto";
import "AkaFesDetailInfo.proto";
import "AlchemySimDetailInfo.proto";
import "AnimalViewDetailInfo.proto";
import "ArenaChallengeActivityDetailInfo.proto";
import "ArenaChallengeV5DetailInfo.proto";
import "AsterActivityDetailInfo.proto";
import "AutoTimeStopDetailInfo.proto";
import "BartenderActivityDetailInfo.proto";
import "BirdBallDetailInfo.proto";
import "BlessingActivityDetailInfo.proto";
import "BlitzRushActivityDetailInfo.proto";
import "BoltbugAbyssDetailInfo.proto";
import "BomberDodocoDetailInfo.proto";
import "BounceConjuringActivityDetailInfo.proto";
import "BrickBreakerDetailInfo.proto";
import "BubbleDramaDetailInfo.proto";
import "BubbleDramaPlayInfo.proto";
import "BulletHellDetailInfo.proto";
import "BuoyantCombatDetailInfo.proto";
import "CeremonyDetailInfo.proto";
import "ChannelerSlabActivityDetailInfo.proto";
import "CharAmusementDetailInfo.proto";
import "ChessActivityDetailInfo.proto";
import "CoinCollectDetailInfo.proto";
import "CollectUnderwaterDetailInfo.proto";
import "CookGameDetailInfo.proto";
import "CooperateChallengeDetailInfo.proto";
import "CrucibleActivityDetailInfo.proto";
import "CrystalLinkActivityDetailInfo.proto";
import "DeliveryActivityDetailInfo.proto";
import "DigActivityDetailInfo.proto";
import "DragonSpineActivityDetailInfo.proto";
import "DuelHeartDetailInfo.proto";
import "EchoShellDetailInfo.proto";
import "EffigyActivityDetailInfo.proto";
import "EffigyChallengeV2DetailInfo.proto";
import "EffigyChallengeV4DetailInfo.proto";
import "EffigyChallengeV5DetailInfo.proto";
import "ElectroherculesBattleDetailInfo.proto";
import "ElectroherculesBattleV3DetailInfo.proto";
import "ExpeditionActivityDetailInfo.proto";
import "FairyTalesDetailInfo.proto";
import "FilmfestDetailInfo.proto";
import "FindHilichurlDetailInfo.proto";
import "FishingJoyDetailInfo.proto";
import "FleurFairActivityDetailInfo.proto";
import "FleurFairV2DetailInfo.proto";
import "FlightActivityDetailInfo.proto";
import "FontaineGatherDetailInfo.proto";
import "FungusFighterDetailInfo.proto";
import "FungusFighterV2DetailInfo.proto";
import "FungusFighterV3DetailInfo.proto";
import "GCGFestivalDetailInfo.proto";
import "GachaActivityDetailInfo.proto";
import "GainBuffDetailInfo.proto";
import "GearActivityDetailInfo.proto";
import "GravenInnocenceDetailInfo.proto";
import "GreatFestivalV2DetailInfo.proto";
import "HachiActivityDetailInfo.proto";
import "HideAndSeekActivityDetailInfo.proto";
import "InstableSprayDetailInfo.proto";
import "IrodoriActivityDetailInfo.proto";
import "IslandPartyDetailInfo.proto";
import "JourneyDetailInfo.proto";
import "LanternRiteActivityDetailInfo.proto";
import "LanternRiteV4DetailInfo.proto";
import "LanternRiteV5DetailInfo.proto";
import "LimitedTimeRewardAreaBannerDetailInfo.proto";
import "LostSamachurlDetailInfo.proto";
import "LuminanceStoneChallengeActivityDetailInfo.proto";
import "LunaRiteDetailInfo.proto";
import "MichiaeMatsuriActivityDetailInfo.proto";
import "MikawaFlowerDetailInfo.proto";
import "MistTrialActivityDetailInfo.proto";
import "MonsterChessDetailInfo.proto";
import "MonsterVsMonsterDetailInfo.proto";
import "MoonfinTrialActivityDetailInfo.proto";
import "MuqadasPotionActivityDetailInfo.proto";
import "MusicGameActivityDetailInfo.proto";
import "NahidaBirthDetailInfo.proto";
import "NatlanArenaDetailInfo.proto";
import "NatlanDrillDetailInfo.proto";
import "NatlanRaceDetailInfo.proto";
import "NatlanTourDetailInfo.proto";
import "PartyDetailInfo.proto";
import "PenumbraAdventureDetailInfo.proto";
import "PhotoActivityDetailInfo.proto";
import "PhotoUnderseaDetailInfo.proto";
import "PlantFlowerActivityDetailInfo.proto";
import "PoetryFestivalDetailInfo.proto";
import "PotionActivityDetailInfo.proto";
import "QuickTimeCombatDetailInfo.proto";
import "RainbowPrinceDetailInfo.proto";
import "RechargeDiskDetailInfo.proto";
import "RockBoardExploreDetailInfo.proto";
import "RogueDiaryActivityDetailInfo.proto";
import "RoguelikeDungeonActivityDetailInfo.proto";
import "SalesmanActivityDetailInfo.proto";
import "SandwormCannonDetailInfo.proto";
import "SeaLampActivityDetailInfo.proto";
import "SeaLampActivityInfo.proto";
import "SeaLampV3DetailInfo.proto";
import "SlimeCannonDetailInfo.proto";
import "SorushTrialDetailInfo.proto";
import "SpiceActivityDetailInfo.proto";
import "StaminaFightDetailInfo.proto";
import "SummerTimeDetailInfo.proto";
import "SummerTimeV2DetailInfo.proto";
import "SumoActivityDetailInfo.proto";
import "TanukiTravelActivityDetailInfo.proto";
import "TeamChainDetailInfo.proto";
import "TowerChallengeDetailInfo.proto";
import "ToyBattleDetailInfo.proto";
import "TreasureHuntV4DetailInfo.proto";
import "TreasureMapActivityDetailInfo.proto";
import "TreasureSeelieActivityDetailInfo.proto";
import "TrialAvatarActivityDetailInfo.proto";
import "UgcActivityDetailInfo.proto";
import "UgcV2DetailInfo.proto";
import "VintageActivityDetailInfo.proto";
import "WaterSpiritActivityDetailInfo.proto";
import "WatergunDetailInfo.proto";
import "WindFieldDetailInfo.proto";
import "WinterCampActivityDetailInfo.proto";
import "_AdventurerStatueDetailInfo.proto";
import "_AquariumDetailInfo.proto";
import "_AutochessDetailInfo.proto";
import "_BlessingV2DetailInfo.proto";
import "_CatcafeDetailInfo.proto";
import "_ClientPlayCurLevelInfo.proto";
import "_ClientPlayData.proto";
import "_ColorBallDetailInfo.proto";
import "_DiversityBattleDetailInfo.proto";
import "_FishBlasterDetailInfo.proto";
import "_GCGAutoBattleCardDetailInfo.proto";
import "_GCGPveDetailInfo.proto";
import "_GCGPveInfiniteDetailInfo.proto";
import "_GCGPvePuzzleDetailInfo.proto";
import "_GoalChallengeDetailInfo.proto";
import "_HideAndSeekV4ActivityDetailInfo.proto";
import "_HolidayResortDetailInfo.proto";
import "_LanternRiteV6DetailInfo.proto";
import "_LeyLineChallengeDetailInfo.proto";
import "_LoliFriendDetailInfo.proto";
import "_MonsterChessV2DetailInfo.proto";
import "_Mvm2DetailInfo.proto";
import "_RankedMatchDetailInfo.proto";
import "_ShortVideoDetailInfo.proto";
import "_SnowRaceDetailInfo.proto";
import "_SumeruAdventureTrainingDetailInfo.proto";
import "_ThemeParkSimDetailInfo.proto";
import "_TowerDefenseDetailInfo.proto";
import "_TpsDefenseDetailInfo.proto";
import "_TradeShowDetailInfo.proto";
import "_WeekActiveDetailInfo.proto";

message ActivityInfo {
	oneof detail {
		SeaLampActivityDetailInfo sam_lamp_info = 1;
		CrucibleActivityDetailInfo crucible_info = 5;
		TrialAvatarActivityDetailInfo trial_avatar_info = 12;
		SalesmanActivityDetailInfo salesman_info = 14;
		PlantFlowerActivityDetailInfo plant_flower_info = 16;
		GainBuffDetailInfo gain_buff_detail_info = 24;
		NatlanArenaDetailInfo natlan_arena_detail_info = 28;
		LanternRiteActivityDetailInfo lantern_rite_activity_info = 35;
		FungusFighterV3DetailInfo fungus_fighter_v3_info = 36;
		_MonsterChessV2DetailInfo monster_chess_v2_detail_info = 42;
		QuickTimeCombatDetailInfo quick_time_combat_info = 54;
		DigActivityDetailInfo dig_info = 57;
		FairyTalesDetailInfo fairy_tales_detail_info = 68;
		ArenaChallengeV5DetailInfo arena_challenge_v5_detail_info = 87;
		SeaLampActivityInfo sea_lamp_info = 102;
		FindHilichurlDetailInfo find_hilichurl_info = 116;
		FungusFighterDetailInfo fungus_fighter_info = 124;
		LuminanceStoneChallengeActivityDetailInfo luminance_stone_challenge_info = 135;
		EffigyActivityDetailInfo effigy_info = 181;
		CoinCollectDetailInfo coin_collect_info = 198;
		LimitedTimeRewardAreaBannerDetailInfo limited_time_reward_area_banner_info = 204;
		FleurFairActivityDetailInfo fleur_fair_info = 237;
		SorushTrialDetailInfo sorush_trial_info = 242;
		RainbowPrinceDetailInfo rainbow_prince_detail_info = 268;
		_LoliFriendDetailInfo loli_friend_detail_info = 271;
		NahidaBirthDetailInfo nahida_birth_detail_info = 302;
		BirdBallDetailInfo bird_ball_detail_info = 303;
		_GCGPveInfiniteDetailInfo gcg_pve_infinite_info = 315;
		IslandPartyDetailInfo island_party_info = 331;
		MoonfinTrialActivityDetailInfo moonfin_trial_info = 333;
		GreatFestivalV2DetailInfo great_festival_v2_detail_info = 360;
		_GoalChallengeDetailInfo goal_challenge_info = 361;
		_LanternRiteV6DetailInfo lantern_rite_v6_info = 399;
		_DiversityBattleDetailInfo diversity_battle_detail_info = 429;
		PenumbraAdventureDetailInfo penumbra_adventure_info = 438;
		MonsterVsMonsterDetailInfo monster_vs_monster_detail_info = 460;
		MonsterChessDetailInfo monster_chess_detail_info = 470;
		FilmfestDetailInfo filmfest_detail_info = 472;
		DeliveryActivityDetailInfo delivery_info = 481;
		RogueDiaryActivityDetailInfo rogue_diary_info = 483;
		PhotoUnderseaDetailInfo photo_undersea_info = 486;
		SeaLampV3DetailInfo sea_lamp_v3_info = 497;
		_TowerDefenseDetailInfo tower_defense_detail_info = 523;
		BulletHellDetailInfo bullet_hell_detail_info = 550;
		BrickBreakerDetailInfo brick_breaker_info = 553;
		TowerChallengeDetailInfo tower_challenge_detail_info = 557;
		_Mvm2DetailInfo mvm2_detail_info = 558;
		_CatcafeDetailInfo catcafe_detail_info = 563;
		MistTrialActivityDetailInfo mist_trial_activity_info = 584;
		SumoActivityDetailInfo sumo_info = 597;
		_GCGPveDetailInfo gcg_pve_info = 619;
		SummerTimeV2DetailInfo summer_time_v2_info = 627;
		AdShootingDetailInfo ad_shooting_detail_info = 631;
		BuoyantCombatDetailInfo buoyant_combat_info = 636;
		_ThemeParkSimDetailInfo theme_park_sim_detail_info = 653;
		AutoTimeStopDetailInfo auto_time_stop_detail_info = 661;
		BomberDodocoDetailInfo bomber_dodoco_detail_info = 672;
		GearActivityDetailInfo gear_info = 674;
		EffigyChallengeV5DetailInfo effigy_challenge_v5_detail_info = 680;
		CooperateChallengeDetailInfo cooperate_challenge_detail_info = 698;
		BartenderActivityDetailInfo bartender_info = 720;
		LostSamachurlDetailInfo lost_samachurl_info = 728;
		ElectroherculesBattleDetailInfo electrohercules_battle_info = 754;
		AcrobaticsBattleDetailInfo acrobatics_battle_detail_info = 767;
		AkaFesDetailInfo aka_fes_info = 783;
		AsterActivityDetailInfo aster_info = 792;
		UgcActivityDetailInfo ugc_info = 875;
		SummerTimeDetailInfo summer_time_info = 890;
		_TpsDefenseDetailInfo tps_defense_detail_info = 892;
		RoguelikeDungeonActivityDetailInfo roguelike_dungoen_info = 915;
		_HolidayResortDetailInfo holiday_resort_detail_info = 924;
		_SnowRaceDetailInfo snow_race_detail_info = 932;
		DragonSpineActivityDetailInfo dragon_spine_info = 948;
		PhotoActivityDetailInfo photo_info = 967;
		_WeekActiveDetailInfo week_active_detail_info = 987;
		_LeyLineChallengeDetailInfo ley_line_challenge_detail_info = 1002;
		_BlessingV2DetailInfo blessing_v2_info = 1013;
		TreasureHuntV4DetailInfo treasure_hunt_v4_info = 1032;
		RechargeDiskDetailInfo recharge_disk_detail_info = 1049;
		PartyDetailInfo party_detail_info = 1052;
		IrodoriActivityDetailInfo irodori_info = 1071;
		HideAndSeekActivityDetailInfo hide_and_seek_info = 1086;
		_AquariumDetailInfo aquarium_detail_info = 1087;
		FleurFairV2DetailInfo fleur_fair_v2_info = 1092;
		GCGFestivalDetailInfo gcg_festival_info = 1107;
		_SumeruAdventureTrainingDetailInfo sumeru_adventure_training_detail_info = 1109;
		CollectUnderwaterDetailInfo collect_underwater_info = 1111;
		WatergunDetailInfo watergun_info = 1119;
		PoetryFestivalDetailInfo poetry_festival_detail_info = 1125;
		ChessActivityDetailInfo chess_info = 1143;
		SlimeCannonDetailInfo slime_cannon_detail_info = 1154;
		NatlanRaceDetailInfo natlan_race_info = 1159;
		StaminaFightDetailInfo stamina_fight_info = 1173;
		WindFieldDetailInfo wind_field_info = 1190;
		FishingJoyDetailInfo fishing_joy_detail_info = 1196;
		TreasureMapActivityDetailInfo treasure_map_info = 1230;
		FungusFighterV2DetailInfo fungus_fighter_v2_info = 1270;
		BlitzRushActivityDetailInfo blitz_rush_info = 1283;
		GachaActivityDetailInfo gacha_info = 1328;
		SpiceActivityDetailInfo spice_info = 1370;
		BounceConjuringActivityDetailInfo bounce_conjuring_info = 1375;
		ChannelerSlabActivityDetailInfo challneler_slab_info = 1413;
		AlchemySimDetailInfo alchemy_sim_detail_info = 1426;
		_TradeShowDetailInfo trade_show_detail_info = 1427;
		_HideAndSeekV4ActivityDetailInfo hide_and_seek_v4_detail_info = 1437;
		BlessingActivityDetailInfo blessing_info = 1441;
		LanternRiteV5DetailInfo lantern_rite_v5_detail_info = 1445;
		_GCGPvePuzzleDetailInfo gcg_pve_puzzle_info = 1451;
		CharAmusementDetailInfo char_amusement_info = 1468;
		EffigyChallengeV4DetailInfo effigy_challenge_v4_info = 1484;
		InstableSprayDetailInfo instable_spray_info = 1496;
		NatlanTourDetailInfo natlan_tour_detail_info = 1497;
		_GCGAutoBattleCardDetailInfo gcg_auto_battle_card_detail_info = 1537;
		BoltbugAbyssDetailInfo boltbug_abyss_detail_info = 1561;
		JourneyDetailInfo journey_info = 1568;
		AnimalViewDetailInfo animal_view_info = 1587;
		_ColorBallDetailInfo color_ball_detail_info = 1590;
		LanternRiteV4DetailInfo lantern_rite_v4_info = 1621;
		TeamChainDetailInfo team_chain_info = 1647;
		SandwormCannonDetailInfo sandworm_cannon_detail_info = 1673;
		ArenaChallengeActivityDetailInfo arena_challenge_info = 1679;
		RockBoardExploreDetailInfo rock_board_explore_info = 1687;
		CookGameDetailInfo cook_game_detail_info = 1695;
		WaterSpiritActivityDetailInfo water_spirit_info = 1709;
		GravenInnocenceDetailInfo graven_innocence_info = 1721;
		_RankedMatchDetailInfo ranked_match_detail_info = 1745;
		DuelHeartDetailInfo duel_heart_info = 1746;
		ExpeditionActivityDetailInfo expedition_info = 1760;
		FontaineGatherDetailInfo fontaine_gather_info = 1765;
		ActivityMultiCharacterDetailInfo activity_multi_character_info = 1774;
		NatlanDrillDetailInfo natlan_drill_info = 1820;
		WinterCampActivityDetailInfo winter_camp_info = 1838;
		TanukiTravelActivityDetailInfo tanuki_travel_activity_info = 1842;
		CeremonyDetailInfo ceremony_info = 1845;
		TreasureSeelieActivityDetailInfo treasure_seelie_info = 1850;
		EchoShellDetailInfo echo_shell_info = 1858;
		LunaRiteDetailInfo luna_rite_info = 1868;
		_AdventurerStatueDetailInfo adventurer_statue_detail_info = 1869;
		HachiActivityDetailInfo hachi_info = 1877;
		MusicGameActivityDetailInfo music_game_info = 1888;
		EffigyChallengeV2DetailInfo effigy_challenge_info = 1891;
		CrystalLinkActivityDetailInfo crystal_link_info = 1896;
		ToyBattleDetailInfo toy_battle_info = 1897;
		PotionActivityDetailInfo potion_info = 1922;
		MichiaeMatsuriActivityDetailInfo michiae_matsuri_info = 1925;
		BubbleDramaDetailInfo bubble_drama_detail_info = 1958;
		VintageActivityDetailInfo vintage_info = 1966;
		_FishBlasterDetailInfo fish_blaster_info = 1970;
		UgcV2DetailInfo ugc_v2_info = 1972;
		_ShortVideoDetailInfo short_video_detail_info = 1973;
		ElectroherculesBattleV3DetailInfo electrohercules_battle_v3_detail_info = 1975;
		FlightActivityDetailInfo flight_info = 1986;
		_AutochessDetailInfo autochess_info = 1993;
		MuqadasPotionActivityDetailInfo muqadas_potion_info = 2002;
		MikawaFlowerDetailInfo mikawa_flower_detail_info = 2044;
	}
	uint32 activity_type = 2;
	uint32 activity_id = 3;
	bool DPOHIMPNKIH = 4;
	repeated uint32 meet_cond_list = 6;
	bool BNIOBCBCGMC = 7;
	repeated ActivityWatcherInfo watcher_info_list = 8;
	bool is_finished = 9;
	uint32 end_time = 10;
	repeated uint32 BFIDMPPFHHC = 11;
	uint32 schedule_id = 13;
	uint32 begin_time = 15;
	bool is_quick_open = 76;
	uint32 score_limit = 359;
	repeated ActivityPushTipsData activity_push_tips_data_list = 541;
	_ClientPlayData _client_play_data = 873;
	map<uint32, uint32> wish_gift_num_map = 878;
	bool CMJNAFAKOCH = 1095;
	uint32 first_day_start_time = 1192;
	repeated uint32 quick_open_pre_quest_list = 1195;
	uint32 DIEFHMGFNIJ = 1235;
	repeated uint32 taken_reward_list = 1311;
	uint32 cur_score = 1429;
	uint32 BDOFMAKFCGO = 1462;
	map<uint32, uint32> activity_coin_map = 1500;
	bool is_hidden = 1577;
	_ClientPlayCurLevelInfo _client_play_cur_level_info = 1596;
	repeated uint64 OPCOMCJHGAJ = 1719;
	uint64 OPPDJKGIKBJ = 1829;
	BubbleDramaPlayInfo bubble_drama_play_info = 1864;
	bool FANKAEHKLBM = 1929;
}
