syntax = "proto3";

option java_package = "emu.grasscutter.net.proto";
option java_outer_classname = "AELIBNHFODDOuterClass";

enum AELIBNHFODD {
	AELIBNHFODD_BEYOND_COMP_TYPE_NONE = 0;
	AELIBNHFODD_BEYOND_COMP_TYPE_CUSTOM_VALUE = 1;
	AELIBNHFODD_BEYOND_COMP_TYPE_TIMER = 3;
	AELIBNHFODD_BEYOND_COMP_TYPE_MOVER = 4;
	AELIBNHFODD_BEYOND_COMP_TYPE_CLIENT_TRIGGER = 5;
	AELIBNHFODD_BEYOND_COMP_TYPE_EFFECT = 6;
	AELIBNHFODD_BEYOND_COMP_TYPE_BORN_POINT = 7;
	AELIBNHFODD_BEYOND_COMP_TYPE_COLLISION = 8;
	AELIBNHFODD_BEYOND_COMP_TYPE_FOLLOW_MOVE = 9;
	AELIBNHFODD_BEYOND_COMP_TYPE_BULLET_MOVE = 11;
	AELIBNHFODD_BEYOND_COMP_TYPE_HIT_DETECTION = 12;
	AELIBNHFODD_BEYOND_COMP_TYPE_CAMERA = 13;
	AELIBNHFODD_BEYOND_COMP_TYPE_ROLE_STATUS = 14;
	AELIBNHFODD_BEYOND_COMP_TYPE_AVATAR_DISTURBER = 15;
	AELIBNHFODD_BEYOND_COMP_TYPE_COUNT_DOWN = 16;
	AELIBNHFODD_BEYOND_COMP_TYPE_OPTION = 17;
	AELIBNHFODD_BEYOND_COMP_TYPE_COMBAT = 18;
	AELIBNHFODD_BEYOND_COMP_TYPE_HITBOX = 19;
	AELIBNHFODD_BEYOND_COMP_TYPE_BULLET_PATTERN = 20;
	AELIBNHFODD_BEYOND_COMP_TYPE_TEMP_ATTACH_POINT = 21;
	AELIBNHFODD_BEYOND_COMP_TYPE_CUSTOM_SKILL = 22;
	AELIBNHFODD_BEYOND_COMP_TYPE_INTEE = 23;
	AELIBNHFODD_BEYOND_COMP_TYPE_MP_ACTION = 24;
	AELIBNHFODD_BEYOND_COMP_TYPE_TAG = 25;
	AELIBNHFODD_BEYOND_COMP_TYPE_ENMITY = 26;
	AELIBNHFODD_BEYOND_COMP_TYPE_NAMEPLATE = 27;
	AELIBNHFODD_BEYOND_COMP_TYPE_TALK = 28;
	AELIBNHFODD_BEYOND_COMP_TYPE_SOUND_EFFECT = 29;
	AELIBNHFODD_BEYOND_COMP_TYPE_MONSTER_PATROL = 30;
	AELIBNHFODD_BEYOND_COMP_TYPE_LEVEL_STATE_MACHINE = 31;
	AELIBNHFODD_BEYOND_COMP_TYPE_MINIMAP_MARK = 32;
	AELIBNHFODD_BEYOND_COMP_TYPE_STUFF_BAG = 33;
	AELIBNHFODD_BEYOND_COMP_TYPE_EQUIP_STUFF_BAG = 34;
	AELIBNHFODD_BEYOND_COMP_TYPE_SHOP = 35;
	AELIBNHFODD_BEYOND_COMP_TYPE_DROP_GATHER = 36;
	AELIBNHFODD_BEYOND_COMP_TYPE_DROP_STUFF = 37;
	AELIBNHFODD_BEYOND_COMP_TYPE_LIGHT_GROUP = 38;
	AELIBNHFODD_BEYOND_COMP_TYPE_SCAN_ENTITY = 39;
	AELIBNHFODD_BEYOND_COMP_TYPE_POP_UP = 40;
	AELIBNHFODD_BEYOND_COMP_TYPE_OBSTACLE = 41;
	AELIBNHFODD_BEYOND_COMP_TYPE_MONSTER_AI_COMP = 42;
	AELIBNHFODD_BEYOND_COMP_TYPE_WATERFALL_COMP = 43;
	AELIBNHFODD_BEYOND_COMP_TYPE_WATER_CUBE_COMP = 44;
	AELIBNHFODD_BEYOND_COMP_TYPE_CURSOR_COLLISION = 45;
	AELIBNHFODD_BEYOND_COMP_TYPE_VEHICLE = 46;
	AELIBNHFODD_BEYOND_COMP_TYPE_ARRAYSIZE = 47;
}
