syntax = "proto3";

option java_package = "emu.grasscutter.net.proto";
option java_outer_classname = "APIBGNMPLHDOuterClass";

enum APIBGNMPLHD {
	APIBGNMPLHD_NONE = 0;
	APIBGNMPLHD_ENTITY = 1;
	APIBGNMPLHD_GUID = 2;
	APIBGNMPLHD_INT32 = 3;
	APIBGNMPLHD_BOOL = 4;
	APIBGNMPLHD_FLOAT = 5;
	APIBGNMPLHD_STRING = 6;
	APIBGNMPLHD_GUID_LIST = 7;
	APIBGNMPLHD_INT32_LIST = 8;
	APIBGNMPLHD_BOOL_LIST = 9;
	APIBGNMPLHD_FLOAT_LIST = 10;
	APIBGNMPLHD_STRING_LIST = 11;
	APIBGNMPLHD_VECTOR3 = 12;
	APIBGNMPLHD_ENTITY_LIST = 13;
	APIBGNMPLHD_ENUM = 14;
	APIBGNMPLHD_VECTOR3_LIST = 15;
	APIBGNMPLHD_VARIABLE = 16;
	APIBGNMPLHD_ARMY = 17;
	APIBGNMPLHD_COMP_TYPE = 18;
	APIBGNMPLHD_CATEGORY_TYPE = 19;
	APIBGNMPLHD_CONFIG_REFERENCE = 20;
	APIBGNMPLHD_ENTITY_REFERENCE = 21;
	APIBGNMPLHD_CONFIG_REFERENCE_LIST = 22;
	APIBGNMPLHD_ENTITY_REFERENCE_LIST = 23;
	APIBGNMPLHD_ARMY_LIST = 24;
	APIBGNMPLHD_STRUCT = 25;
	APIBGNMPLHD_STRUCT_LIST = 26;
	APIBGNMPLHD_DICT = 27;
	APIBGNMPLHD_CUSTOM_VALUE_SNAPSHOT = 28;
	APIBGNMPLHD_ENUM_LIST = 29;
	APIBGNMPLHD_MAX = 50;
}
