syntax = "proto3";

option java_package = "emu.grasscutter.net.proto";
option java_outer_classname = "DoGachaRspOuterClass";

import "GachaItem.proto";

message DoGachaRsp {
	uint32 ten_cost_item_num = 50000;
	uint32 left_gacha_times = 50001;
	uint32 gacha_times = 11;
	uint32 gacha_times_limit = 50002;
	int32 retcode = 4;
	uint32 cost_item_id = 50003;
	uint32 gacha_type = 1;
	uint32 gacha_schedule_id = 6;
	uint32 wish_progress = 50004;
	uint32 cost_item_num = 50005;
	uint32 ten_cost_item_id = 50006;
	uint32 wish_item_id = 50007;
	repeated GachaItem gacha_item_list = 13;
	uint32 wish_max_progress = 50008;
	uint32 new_gacha_random = 2;
	uint32 cur_schedule_daily_gacha_times = 50009;
	bool is_under_minors_restrict = 50010;
	bool is_under_general_restrict = 50011;
	bool is_epitomized = 50012;
	uint32 daily_gacha_times = 1464;
}
