syntax = "proto3";

option java_package = "emu.grasscutter.net.proto";
option java_outer_classname = "DungeonSettleNotifyOuterClass";

import "BladeDanceSettleInfo.proto";
import "ChannellerSlabLoopDungeonResultInfo.proto";
import "CrystalLinkDungeonSettleInfo.proto";
import "DungeonSettleExhibitionInfo.proto";
import "EffigyChallengeDungeonResultInfo.proto";
import "EffigyChallengeV2SettleInfo.proto";
import "FungusFighterV2SettleInfo.proto";
import "InstableSprayDungeonSettleInfo.proto";
import "MultiCharacterDungeonSettleInfo.proto";
import "PacmanSettleInfo.proto";
import "ParamList.proto";
import "RoguelikeDungeonSettleInfo.proto";
import "StrengthenPointData.proto";
import "SummerTimeV2DungeonSettleInfo.proto";
import "TeamChainSettleInfo.proto";
import "TowerLevelEndNotify.proto";
import "TrialAvatarFirstPassDungeonNotify.proto";
import "WindFieldDungeonSettleInfo.proto";
import "_AcrobaticsBattleSettleInfo.proto";
import "_AdShootingSettleInfo.proto";
import "_AdventurerStatueDungeonSettleInfo.proto";
import "_AquariumDivingDungeonSettleInfo.proto";
import "_AquariumFishingDungeonSettleInfo.proto";
import "_AutoTimeStopSettleInfo.proto";
import "_BadgetBattleSettleInfo.proto";
import "_BladeHeartDungeonSettleInfo.proto";
import "_BomberDodocoSettleInfo.proto";
import "_BulletHellSettleInfo.proto";
import "_CeremonyBattleSettleInfo.proto";
import "_CharMasterSettleInfo.proto";
import "_CooperateChallengeSettleInfo.proto";
import "_DiversityBattleSettleInfo.proto";
import "_EffigyChallengeV5SettleInfo.proto";
import "_FairyTalesCombatSettleInfo.proto";
import "_FeverBattleSettleInfo.proto";
import "_FilmfestBattleSettleInfo.proto";
import "_FilmfestSniperSettleInfo.proto";
import "_FungusFighterV3SettleInfo.proto";
import "_GainBuffSettleInfo.proto";
import "_GalleryContextEntry.proto";
import "_GoalChallengeSettleInfo.proto";
import "_HumanDragonPuzzleSettleInfo.proto";
import "_InspirationSpurtDungeonSettleInfo.proto";
import "_LanternRiteV6BattleSettleInfo.proto";
import "_LanternRiteV6ParkourSettleInfo.proto";
import "_LoliBattleDungeonSettleInfo.proto";
import "_LoliGolfDungeonSettleInfo.proto";
import "_LoliRunDungeonSettleInfo.proto";
import "_LostSamachurlSneakSettleInfo.proto";
import "_MapMarkSettleInfo.proto";
import "_MistTrialSettleInfo.proto";
import "_MonsterSnapSettleInfo.proto";
import "_MusicPartySettleInfo.proto";
import "_Mvm2PveSettleInfo.proto";
import "_Mvm2SimulateSettleInfo.proto";
import "_NatlanArenaSettleInfo.proto";
import "_NatlanDragonPartySettleInfo.proto";
import "_NatlanDrillBattleSettleInfo.proto";
import "_NodkraiTourHackSettleInfo.proto";
import "_NodkraiTourParkourSettleInfo.proto";
import "_OneShotDungeonSettleInfo.proto";
import "_QuickTimeCombatSettleInfo.proto";
import "_RankedMatchPuzzleSettleInfo.proto";
import "_RankedMatchShootingSettleInfo.proto";
import "_RankedMatchSnowBallSettleInfo.proto";
import "_RankedMatchTrainSettleInfo.proto";
import "_RechargeDiskSettleInfo.proto";
import "_RoleCombatSettleInfo.proto";
import "_Saurus1V3SettleInfo.proto";
import "_ShortVideoSettleInfo.proto";
import "_SlimeCannonSettleInfo.proto";
import "_SnowRaceCombatSettleInfo.proto";
import "_SnowRaceParkourSettleInfo.proto";
import "_SnowRaceThrowSettleInfo.proto";
import "_StaminaFightSettleInfo.proto";
import "_SumeruAdventureTrainingSettleInfo.proto";
import "_ThemeParkParkourSettleInfo.proto";
import "_ThemeParkTriathlonSettleInfo.proto";
import "_TowerChallengeSettleInfo.proto";
import "_TowerDefenseSettleInfo.proto";
import "_TpsDefenseSettleInfo.proto";
import "_TpsMercenariesSettleInfo.proto";
import "_TradeShowBattleSettleInfo.proto";
import "_TradeShowStgSettleInfo.proto";
import "_TradeShowTdSettleInfo.proto";

message DungeonSettleNotify {
	oneof detail {
		_NatlanDrillBattleSettleInfo natlan_drill_battle_settle_info = 17;
		_TowerChallengeSettleInfo tower_challenge_settle_info = 76;
		RoguelikeDungeonSettleInfo roguelike_dungeon_settle_info = 93;
		_AutoTimeStopSettleInfo auto_time_stop_settle_info = 114;
		_SnowRaceParkourSettleInfo snow_race_parkour_settle_info = 143;
		_NodkraiTourParkourSettleInfo nodkrai_tour_parkour_settle_info = 162;
		_NatlanDragonPartySettleInfo natlan_dragon_party_settle_info = 207;
		_NodkraiTourHackSettleInfo nodkrai_tour_hack_settle_info = 212;
		_AdShootingSettleInfo ad_shooting_settle_info = 241;
		InstableSprayDungeonSettleInfo instable_spray_settle_info = 252;
		_Mvm2SimulateSettleInfo mvm2_simulate_settle_info = 260;
		_BomberDodocoSettleInfo bomber_dodoco_settle_info = 264;
		_TradeShowBattleSettleInfo trade_show_battle_settle_info = 265;
		_RechargeDiskSettleInfo recharge_disk_settle_info = 344;
		_RoleCombatSettleInfo role_combat_settle_info = 373;
		_StaminaFightSettleInfo stamina_fight_settle_info = 382;
		_AcrobaticsBattleSettleInfo acrobatics_battle_settle_info = 396;
		_CharMasterSettleInfo char_master_settle_info = 401;
		_FilmfestSniperSettleInfo filmfest_sniper_settle_info = 432;
		_CeremonyBattleSettleInfo ceremony_battle_settle_info = 505;
		_GainBuffSettleInfo gain_buff_settle_info = 506;
		WindFieldDungeonSettleInfo wind_field_dungeon_settle_info = 517;
		_SnowRaceCombatSettleInfo snow_race_combat_settle_info = 570;
		TeamChainSettleInfo team_chain_settle_info = 601;
		_RankedMatchSnowBallSettleInfo ranked_match_snow_ball_settle_info = 635;
		_RankedMatchShootingSettleInfo ranked_match_shooting_settle_info = 713;
		_MusicPartySettleInfo music_party_settle_info = 730;
		MultiCharacterDungeonSettleInfo multi_character_dungeon_settle_info = 739;
		_NatlanArenaSettleInfo natlan_arena_settle_info = 750;
		_GalleryContextEntry gallery_context_entry = 806;
		_TpsMercenariesSettleInfo tps_mercenaries_settle_info = 858;
		_CooperateChallengeSettleInfo cooperate_challenge_settle_info = 869;
		BladeDanceSettleInfo blade_dance_settle_info = 920;
		EffigyChallengeV2SettleInfo effigy_challenge_v2_settle_info = 934;
		TowerLevelEndNotify tower_level_end_notify = 948;
		_RankedMatchPuzzleSettleInfo ranked_match_puzzle_settle_info = 961;
		_AdventurerStatueDungeonSettleInfo adventurer_statue_dungeon_settle_info = 966;
		_FilmfestBattleSettleInfo filmfest_battle_settle_info = 988;
		_RankedMatchTrainSettleInfo ranked_match_train_settle_info = 1054;
		_TowerDefenseSettleInfo tower_defense_settle_info = 1065;
		_SumeruAdventureTrainingSettleInfo sumeru_adventure_training_settle_info = 1068;
		PacmanSettleInfo pacman_settle_info = 1071;
		_LoliGolfDungeonSettleInfo loli_golf_dungeon_settle_info = 1076;
		_ThemeParkParkourSettleInfo theme_park_parkour_settle_info = 1093;
		_Saurus1V3SettleInfo saurus1v3_settle_info = 1111;
		_EffigyChallengeV5SettleInfo effigy_challenge_v5_settle_info = 1156;
		_LostSamachurlSneakSettleInfo lost_samachurl_sneak_settle_info = 1157;
		_MistTrialSettleInfo mist_trial_settle_info = 1180;
		EffigyChallengeDungeonResultInfo effigy_challenge_dungeon_result_info = 1185;
		_OneShotDungeonSettleInfo one_shot_dungeon_settle_info = 1238;
		_BladeHeartDungeonSettleInfo blade_heart_dungeon_settle_info = 1244;
		_Mvm2PveSettleInfo mvm2_pve_settle_info = 1246;
		_LanternRiteV6BattleSettleInfo lantern_rite_v6_battle_settle_info = 1268;
		SummerTimeV2DungeonSettleInfo summer_time_v2_dungeon_settle_info = 1329;
		_DiversityBattleSettleInfo diversity_battle_settle_info = 1335;
		_LanternRiteV6ParkourSettleInfo lantern_rite_v6_parkour_settle_info = 1387;
		_BulletHellSettleInfo bullet_hell_settle_info = 1422;
		_ThemeParkTriathlonSettleInfo theme_park_triathlon_settle_info = 1451;
		_AquariumDivingDungeonSettleInfo aquarium_diving_dungeon_settle_info = 1457;
		_AquariumFishingDungeonSettleInfo aquarium_fishing_dungeon_settle_info = 1467;
		_MapMarkSettleInfo map_mark_settle_info = 1483;
		_GoalChallengeSettleInfo goal_challenge_settle_info = 1571;
		_SnowRaceThrowSettleInfo snow_race_throw_settle_info = 1577;
		_FeverBattleSettleInfo fever_battle_settle_info = 1580;
		_FairyTalesCombatSettleInfo fairy_tales_combat_settle_info = 1621;
		CrystalLinkDungeonSettleInfo crystal_link_settle_info = 1646;
		_ShortVideoSettleInfo short_video_settle_info = 1667;
		_BadgetBattleSettleInfo badget_battle_settle_info = 1682;
		_MonsterSnapSettleInfo monster_snap_settle_info = 1721;
		_TpsDefenseSettleInfo tps_defense_settle_info = 1743;
		_QuickTimeCombatSettleInfo quick_time_combat_settle_info = 1758;
		ChannellerSlabLoopDungeonResultInfo channeller_slab_loop_dungeon_result_info = 1762;
		_TradeShowTdSettleInfo trade_show_td_settle_info = 1848;
		TrialAvatarFirstPassDungeonNotify trial_avatar_first_pass_dungeon_notify = 1862;
		FungusFighterV2SettleInfo fungus_fighter_v2_settle_info = 1866;
		_LoliBattleDungeonSettleInfo loli_battle_dungeon_settle_info = 1867;
		_SlimeCannonSettleInfo slime_cannon_settle_info = 1896;
		_LoliRunDungeonSettleInfo loli_run_dungeon_settle_info = 1897;
		_InspirationSpurtDungeonSettleInfo inspiration_spurt_dungeon_settle_info = 1985;
		_TradeShowStgSettleInfo trade_show_stg_settle_info = 1997;
		_FungusFighterV3SettleInfo fungus_fighter_v3_settle_info = 2035;
		_HumanDragonPuzzleSettleInfo human_dragon_puzzle_settle_info = 2041;
	}
	uint32 result = 1;
	uint32 use_time = 2;
	map<uint32, StrengthenPointData> strengthen_point_data_map = 3;
	uint32 close_time = 4;
	map<uint32, ParamList> settle_show = 6;
	repeated uint32 player_uid_list = 7;
	repeated uint32 fail_cond_list = 8;
	uint32 create_player_uid = 11;
	repeated DungeonSettleExhibitionInfo exhibition_info_list = 12;
	uint32 dungeon_id = 13;
	bool is_success = 14;
}
