syntax = "proto3";

option java_package = "emu.grasscutter.net.proto";
option java_outer_classname = "GetPlayerTokenRspOuterClass";

import "StopServerInfo.proto";

message GetPlayerTokenRsp {
	bytes security_cmd_buffer = 1;
	string msg = 2;
	string account_uid = 3;
	uint32 uid = 4;
	int32 retcode = 5;
	bytes extra_bin_data = 6;
	uint32 gm_uid = 7;
	uint32 platform_type = 8;
	string token = 9;
	string secret_key = 10;
	bool is_proficient_player = 11;
	uint32 black_uid_end_time = 12;
	uint32 account_type = 13;
	bool is_guest = 14;
	uint64 secret_key_seed = 15;
	uint32 reg_platform = 201;
	string server_rand_key = 208;
	bool CGPIOKGGDPB = 340;
	string _xuid = 342;
	string birthday = 496;
	uint32 tag = 512;
	uint32 authkey_ver = 530;
	uint32 minors_reg_min_age = 586;
	uint32 sub_channel_id = 627;
	string auth_appid = 660;
	bytes _security_file = 663;
	string sign = 708;
	bool KONAINKDJCN = 851;
	string client_version_random_key = 852;
	bool MGNAAEGCEDL = 853;
	repeated uint32 finish_collection_id_list = 1218;
	string country_code = 1265;
	string psn_id = 1268;
	uint32 channel_id = 1442;
	StopServerInfo stop_server = 1465;
	string client_ip_str = 1477;
	string game_biz = 1569;
	string authkey = 1589;
	string KONDBANCCAH = 1840;
	uint32 key_id = 1878;
	uint32 sign_type = 1935;
}
