syntax = "proto3";

option java_package = "emu.grasscutter.net.proto";
option java_outer_classname = "JEOKDCIGCFPOuterClass";

enum JEOKDCIGCFP {
	JEOKDCIGCFP_BEYOND_ENUM_NONE = 0;
	JEOKDCIGCFP_BEYOND_COMPARE_OPERATOR_EQUAL = 100;
	JEOKDCIGCFP_BEYOND_COMPARE_OPERATOR_LESS = 101;
	JEOKDCIGCFP_BEYOND_COMPARE_OPERATOR_LESS_EQUAL = 102;
	JEOKDCIGCFP_BEYOND_COMPARE_OPERATOR_GREATER = 103;
	JEOKDCIGCFP_BEYOND_COMPARE_OPERATOR_GREATER_EQUAL = 104;
	JEOKDCIGCFP_BEYOND_COMPARE_OPERATOR_NOT_EQUAL = 105;
	JEOKDCIGCFP_BEYOND_LOGIC_OPERATOR_AND = 200;
	JEOKDCIGCFP_BEYOND_LOGIC_OPERATOR_OR = 201;
	JEOKDCIGCFP_BEYOND_LOGIC_OPERATOR_XOR = 202;
	JEOKDCIGCFP_BEYOND_LOGIC_OPERATOR_NOT = 203;
	JEOKDCIGCFP_BEYOND_NUMERICAL_OPERATOR_ADD = 300;
	JEOKDCIGCFP_BEYOND_NUMERICAL_OPERATOR_SUBTRACT = 301;
	JEOKDCIGCFP_BEYOND_NUMERICAL_OPERATOR_MULTIPLY = 302;
	JEOKDCIGCFP_BEYOND_NUMERICAL_OPERATOR_DIVID = 303;
	JEOKDCIGCFP_BEYOND_NUMERICAL_OPERATOR_MODULO = 304;
	JEOKDCIGCFP_BEYOND_NUMERICAL_OPERATOR_POWER = 305;
	JEOKDCIGCFP_BEYOND_NUMERICAL_OPERATOR_MAX = 306;
	JEOKDCIGCFP_BEYOND_NUMERICAL_OPERATOR_MIN = 307;
	JEOKDCIGCFP_BEYOND_NUMERICAL_OPERATOR_LOG = 308;
	JEOKDCIGCFP_BEYOND_NUMERICAL_OPERATOR_ABS = 309;
	JEOKDCIGCFP_BEYOND_NUMERICAL_OPERATOR_SIGN = 310;
	JEOKDCIGCFP_BEYOND_NUMERICAL_OPERATOR_SQRT = 311;
	JEOKDCIGCFP_BEYOND_NUMERICAL_OPERATOR_CLAMP = 312;
	JEOKDCIGCFP_BEYOND_ATTACK_SHAPE_BOX = 400;
	JEOKDCIGCFP_BEYOND_ATTACK_SHAPE_SPHERE = 401;
	JEOKDCIGCFP_BEYOND_ATTACK_SHAPE_CIRCLE = 402;
	JEOKDCIGCFP_BEYOND_CIRCLE_DETECT_DIRECTION_CENTER_TO_SIDE = 450;
	JEOKDCIGCFP_BEYOND_CIRCLE_DETECT_DIRECTION_CLOCKWISE = 451;
	JEOKDCIGCFP_BEYOND_CIRCLE_DETECT_DIRECTION_COUNTERCLOCKWISE = 452;
	JEOKDCIGCFP_BEYOND_ENTITY_LIFE_STATE_LIVE = 500;
	JEOKDCIGCFP_BEYOND_ENTITY_LIFE_STATE_DEAD = 501;
	JEOKDCIGCFP_BEYOND_ORDER_RULE_ASCENDING = 600;
	JEOKDCIGCFP_BEYOND_ORDER_RULE_DESCENDING = 601;
	JEOKDCIGCFP_BEYOND_ORDER_RULE_RANDOM = 602;
	JEOKDCIGCFP_BEYOND_ROUND_RULE_CEILING = 700;
	JEOKDCIGCFP_BEYOND_ROUND_RULE_FLOOR = 701;
	JEOKDCIGCFP_BEYOND_ROUND_RULE_ROUND = 702;
	JEOKDCIGCFP_BEYOND_ROUND_RULE_TRUNCATE = 703;
	JEOKDCIGCFP_BEYOND_CONVERTOR_INT32_BOOL = 800;
	JEOKDCIGCFP_BEYOND_CONVERTOR_INT32_FLOAT = 801;
	JEOKDCIGCFP_BEYOND_CONVERTOR_INT32_STRING = 802;
	JEOKDCIGCFP_BEYOND_CONVERTOR_ENTITY_STRING = 803;
	JEOKDCIGCFP_BEYOND_CONVERTOR_GUID_STRING = 804;
	JEOKDCIGCFP_BEYOND_CONVERTOR_BOOL_INT32 = 805;
	JEOKDCIGCFP_BEYOND_CONVERTOR_BOOL_STRING = 806;
	JEOKDCIGCFP_BEYOND_CONVERTOR_FLOAT_INT32 = 807;
	JEOKDCIGCFP_BEYOND_CONVERTOR_FLOAT_STRING = 808;
	JEOKDCIGCFP_BEYOND_CONVERTOR_VECTOR3_STRING = 809;
	JEOKDCIGCFP_BEYOND_CONVERTOR_ARMY_STRING = 810;
	JEOKDCIGCFP_BEYOND_ENTITY_POINT_TYPE_VECTOR = 900;
	JEOKDCIGCFP_BEYOND_ENTITY_POINT_TYPE_CURVE = 901;
	JEOKDCIGCFP_BEYOND_ENTITY_MOVE_TYPE_ONEWAY = 1000;
	JEOKDCIGCFP_BEYOND_ENTITY_MOVE_TYPE_RECIPROCATE = 1001;
	JEOKDCIGCFP_BEYOND_ENTITY_MOVE_TYPE_LOOP = 1002;
	JEOKDCIGCFP_BEYOND_FOLLOW_TYPE_DEFAULT = 1100;
	JEOKDCIGCFP_BEYOND_FOLLOW_TYPE_POS = 1101;
	JEOKDCIGCFP_BEYOND_FOLLOW_TYPE_ROT = 1102;
	JEOKDCIGCFP_BEYOND_FOLLOW_COORDINATE_RELATIVE = 1200;
	JEOKDCIGCFP_BEYOND_FOLLOW_COORDINATE_ABSOLUTE = 1201;
	JEOKDCIGCFP_BEYOND_ELEMENT_TYPE_NONE = 1300;
	JEOKDCIGCFP_BEYOND_ELEMENT_TYPE_FIRE = 1301;
	JEOKDCIGCFP_BEYOND_ELEMENT_TYPE_WATER = 1302;
	JEOKDCIGCFP_BEYOND_ELEMENT_TYPE_WIND = 1303;
	JEOKDCIGCFP_BEYOND_ELEMENT_TYPE_THUNDER = 1304;
	JEOKDCIGCFP_BEYOND_ELEMENT_TYPE_GRASS = 1305;
	JEOKDCIGCFP_BEYOND_ELEMENT_TYPE_ICE = 1306;
	JEOKDCIGCFP_BEYOND_ELEMENT_TYPE_ROCK = 1307;
	JEOKDCIGCFP_BEYOND_ENTITY_TYPE_LEVEL = 1401;
	JEOKDCIGCFP_BEYOND_ENTITY_TYPE_GADGET = 1402;
	JEOKDCIGCFP_BEYOND_ENTITY_TYPE_PLAYER = 1403;
	JEOKDCIGCFP_BEYOND_ENTITY_TYPE_AVATAR = 1404;
	JEOKDCIGCFP_BEYOND_ENTITY_TYPE_MONSTER = 1405;
	JEOKDCIGCFP_BEYOND_ROLE_STATUS_REASON_ADD_FAILED_EXCEPTION = 1500;
	JEOKDCIGCFP_BEYOND_ROLE_STATUS_REASON_ADD_FAILED_RESISTED = 1501;
	JEOKDCIGCFP_BEYOND_ROLE_STATUS_REASON_ADD_FAILED_OVERSLOTS = 1502;
	JEOKDCIGCFP_BEYOND_ROLE_STATUS_REASON_ADD_FAILED_OVERCOUNT = 1503;
	JEOKDCIGCFP_BEYOND_ROLE_STATUS_REASON_ADD_SUCC_NEW_SLOT = 1504;
	JEOKDCIGCFP_BEYOND_ROLE_STATUS_REASON_ADD_SUCC_UPDATE = 1505;
	JEOKDCIGCFP_BEYOND_ROLE_STATUS_REASON_REMOVE_SLOT_REPLACED = 1506;
	JEOKDCIGCFP_BEYOND_ROLE_STATUS_REASON_REMOVE_LIFE_END = 1507;
	JEOKDCIGCFP_BEYOND_ROLE_STATUS_REASON_REMOVE_DISPERSE = 1508;
	JEOKDCIGCFP_BEYOND_ROLE_STATUS_REASON_REMOVE_CANCEL = 1509;
	JEOKDCIGCFP_BEYOND_ROLE_STATUS_REASON_REMOVE_DUTY_CHANGE = 1510;
	JEOKDCIGCFP_BEYOND_ROLE_STATUS_REASON_REMOVE_AFFIX_DEACTIVE = 1511;
	JEOKDCIGCFP_BEYOND_ROLE_STATUS_REASON_REMOVE_SHIELD_BREAK = 1512;
	JEOKDCIGCFP_BEYOND_ROLE_STATUS_REMOVE_POLICY_ALL = 1540;
	JEOKDCIGCFP_BEYOND_ROLE_STATUS_REMOVE_POLICY_SINGLE = 1541;
	JEOKDCIGCFP_BEYOND_REVIVE_POINT_SELECT_POLICY_NEAREST = 1601;
	JEOKDCIGCFP_BEYOND_REVIVE_POINT_SELECT_POLICY_LAST_ACTIVE = 1602;
	JEOKDCIGCFP_BEYOND_REVIVE_POINT_SELECT_POLICY_PRIORITY = 1603;
	JEOKDCIGCFP_BEYOND_REVIVE_POINT_SELECT_POLICY_RANDOM = 1604;
	JEOKDCIGCFP_BEYOND_DIE_REASON_BEYOND_BLUEPRINT = 1605;
	JEOKDCIGCFP_BEYOND_DIE_REASON_NORMAL = 1606;
	JEOKDCIGCFP_BEYOND_DIE_REASON_SPECIAL = 1607;
	JEOKDCIGCFP_BEYOND_TRIGONOMETRIC_OP_CAL_COS = 1700;
	JEOKDCIGCFP_BEYOND_TRIGONOMETRIC_OP_CAL_SIN = 1701;
	JEOKDCIGCFP_BEYOND_TRIGONOMETRIC_OP_CAL_TAN = 1702;
	JEOKDCIGCFP_BEYOND_TRIGONOMETRIC_OP_CAL_ACOS = 1703;
	JEOKDCIGCFP_BEYOND_TRIGONOMETRIC_OP_CAL_ASIN = 1704;
	JEOKDCIGCFP_BEYOND_TRIGONOMETRIC_OP_CAL_ATAN = 1705;
	JEOKDCIGCFP_BEYOND_TRIGONOMETRIC_OP_CAL_RAD2_DAG = 1706;
	JEOKDCIGCFP_BEYOND_TRIGONOMETRIC_OP_CAL_DAG2_RAD = 1707;
	JEOKDCIGCFP_BEYOND_AVATAR_DISTURBER_TRAVELLER = 1800;
	JEOKDCIGCFP_BEYOND_AVATAR_DISTURBER_FIELD = 1801;
	JEOKDCIGCFP_BEYOND_AVATAR_DISTURBER_EJECT = 1802;
	JEOKDCIGCFP_BEYOND_AVATAR_DISTURBER_DRAG = 1803;
	JEOKDCIGCFP_BEYOND_AVATAR_DISTURBER_RADIATE = 1810;
	JEOKDCIGCFP_BEYOND_AVATAR_DISTURBER_SINGLE_DIR = 1811;
	JEOKDCIGCFP_BEYOND_UI_SWITCH_STATUS_OFF = 1900;
	JEOKDCIGCFP_BEYOND_UI_SWITCH_STATUS_ON = 1901;
	JEOKDCIGCFP_BEYOND_UI_SWITCH_STATUS_HIDE = 1902;
	JEOKDCIGCFP_BEYOND_MP_ACTION_TARGET_TYPE_NONE = 2000;
	JEOKDCIGCFP_BEYOND_MP_ACTION_TARGET_TYPE_ALIANCE = 2001;
	JEOKDCIGCFP_BEYOND_MP_ACTION_TARGET_TYPE_ENEMY = 2002;
	JEOKDCIGCFP_BEYOND_MP_ACTION_TARGET_TYPE_SELF = 2003;
	JEOKDCIGCFP_BEYOND_MP_ACTION_TARGET_TYPE_SELF_CAMP = 2004;
	JEOKDCIGCFP_BEYOND_MP_ACTION_TARGET_TYPE_ALL = 2005;
	JEOKDCIGCFP_BEYOND_MP_ACTION_TARGET_TYPE_ALL_EXCEPT_SELF = 2006;
	JEOKDCIGCFP_BEYOND_MP_ACTION_TARGET_TYPE_ALLIANCE_INCLUDE_SELF = 2007;
	JEOKDCIGCFP_BEYOND_HIT_DETECTION_TRIGGER_NONE = 2100;
	JEOKDCIGCFP_BEYOND_HIT_DETECTION_TRIGGER_ONCE = 2101;
	JEOKDCIGCFP_BEYOND_HIT_DETECTION_TRIGGER_NO_REPEAT = 2102;
	JEOKDCIGCFP_BEYOND_HIT_DETECTION_TRIGGER_ALWAYS = 2103;
	JEOKDCIGCFP_BEYOND_STRIKE_TYPE_NONE = 2200;
	JEOKDCIGCFP_BEYOND_STRIKE_TYPE_DEFAULT = 2201;
	JEOKDCIGCFP_BEYOND_STRIKE_TYPE_SLASH = 2202;
	JEOKDCIGCFP_BEYOND_STRIKE_TYPE_BLUNT = 2203;
	JEOKDCIGCFP_BEYOND_STRIKE_TYPE_PIERCE = 2204;
	JEOKDCIGCFP_BEYOND_STRIKE_TYPE_SPEAR = 2205;
	JEOKDCIGCFP_BEYOND_ATTACK_TYPE_NONE = 2300;
	JEOKDCIGCFP_BEYOND_ATTACK_TYPE_MELEE = 2301;
	JEOKDCIGCFP_BEYOND_ATTACK_TYPE_RANGE = 2302;
	JEOKDCIGCFP_BEYOND_ATTACK_TYPE_DEFAULT = 2303;
	JEOKDCIGCFP_BEYOND_HIT_IMPULSE_TYPE_DEFAULT = 2400;
	JEOKDCIGCFP_BEYOND_HIT_IMPULSE_TYPE_LV0 = 2401;
	JEOKDCIGCFP_BEYOND_HIT_IMPULSE_TYPE_LV1 = 2402;
	JEOKDCIGCFP_BEYOND_HIT_IMPULSE_TYPE_LV2 = 2403;
	JEOKDCIGCFP_BEYOND_HIT_IMPULSE_TYPE_LV3 = 2404;
	JEOKDCIGCFP_BEYOND_HIT_IMPULSE_TYPE_LV4 = 2405;
	JEOKDCIGCFP_BEYOND_HIT_IMPULSE_TYPE_LV5 = 2406;
	JEOKDCIGCFP_BEYOND_HIT_IMPULSE_TYPE_LV6 = 2407;
	JEOKDCIGCFP_BEYOND_HIT_IMPULSE_TYPE_LV7 = 2408;
	JEOKDCIGCFP_BEYOND_HIT_IMPULSE_TYPE_LV8 = 2409;
	JEOKDCIGCFP_BEYOND_HIT_IMPULSE_TYPE_LV9 = 2410;
	JEOKDCIGCFP_BEYOND_RETREAT_TYPE_NONE = 2500;
	JEOKDCIGCFP_BEYOND_RETREAT_TYPE_BY_ATTACKER = 2501;
	JEOKDCIGCFP_BEYOND_RETREAT_TYPE_BY_HIT_DIRECTION = 2502;
	JEOKDCIGCFP_BEYOND_RETREAT_TYPE_BY_ORIGINAL_OWNER = 2503;
	JEOKDCIGCFP_BEYOND_RETREAT_TYPE_BY_TANGENT = 2504;
	JEOKDCIGCFP_BEYOND_RETREAT_TYPE_BY_HIT_DIRECTION_INVERSE = 2505;
	JEOKDCIGCFP_BEYOND_RETREAT_TYPE_BY_ATTACKER_FORWARD = 2506;
	JEOKDCIGCFP_BEYOND_RETREAT_TYPE_BY_ATTACKER_INVERSE = 2507;
	JEOKDCIGCFP_BEYOND_CHECK_HIT_LAYER_TYPE_NONE = 2600;
	JEOKDCIGCFP_BEYOND_CHECK_HIT_LAYER_TYPE_ONLY_HITBOX = 2601;
	JEOKDCIGCFP_BEYOND_CHECK_HIT_LAYER_TYPE_ONLY_SCENE = 2602;
	JEOKDCIGCFP_BEYOND_CHECK_HIT_LAYER_TYPE_ONLY_MASSIVE = 2603;
	JEOKDCIGCFP_BEYOND_CHECK_HIT_LAYER_TYPE_ALL = 2604;
	JEOKDCIGCFP_BEYOND_CHECK_HIT_LAYER_TYPE_GADGET_COLLIDER = 2605;
	JEOKDCIGCFP_BEYOND_CHECK_HIT_LAYER_TYPE_RAYCAST_COLLISION_BOX = 2606;
	JEOKDCIGCFP_BEYOND_VELOCITY_FORCE_TYPE_RETREAT_TYPE = 2700;
	JEOKDCIGCFP_BEYOND_VELOCITY_FORCE_TYPE_RETREAT_AIR_TYPE = 2701;
	JEOKDCIGCFP_BEYOND_VELOCITY_FORCE_TYPE_RUSH_MOVE_TYPE = 2702;
	JEOKDCIGCFP_BEYOND_VELOCITY_FORCE_TYPE_WIND_ZONE_TYPE = 2703;
	JEOKDCIGCFP_BEYOND_VELOCITY_FORCE_TYPE_AIR_FLOW_TYPE = 2704;
	JEOKDCIGCFP_BEYOND_VELOCITY_FORCE_TYPE_RISE_TYPE = 2705;
	JEOKDCIGCFP_BEYOND_VELOCITY_FORCE_TYPE_SPEED_UP_TYPE = 2706;
	JEOKDCIGCFP_BEYOND_VELOCITY_FORCE_TYPE_AIRFLOW_ACC_TYPE = 2707;
	JEOKDCIGCFP_BEYOND_VELOCITY_FORCE_TYPE_INERTIA_TYPE = 2708;
	JEOKDCIGCFP_BEYOND_VELOCITY_FORCE_TYPE_FIXED_RUSH_MOVE_TYPE = 2709;
	JEOKDCIGCFP_BEYOND_VELOCITY_FORCE_TYPE_LIGHT_CORE_TYPE_NORMAL = 2710;
	JEOKDCIGCFP_BEYOND_VELOCITY_FORCE_TYPE_LIGHT_CORE_TYPE_ACCELERATE = 2711;
	JEOKDCIGCFP_BEYOND_VELOCITY_FORCE_TYPE_GOROU_ZONE_TYPE = 2712;
	JEOKDCIGCFP_BEYOND_VELOCITY_FORCE_TYPE_UGC_DIRECTED_FORCE_TYPE = 2713;
	JEOKDCIGCFP_BEYOND_VELOCITY_FORCE_TYPE_TRAMPOLINE_FORCE_TYPE = 2714;
	JEOKDCIGCFP_BEYOND_VELOCITY_FORCE_TYPE_GRAPPLING_HOOK_MOVE_TYPE = 2715;
	JEOKDCIGCFP_BEYOND_VELOCITY_FORCE_TYPE_WIDGET_AIRFLOW_TYPE = 2716;
	JEOKDCIGCFP_BEYOND_VELOCITY_FORCE_TYPE_LINEAR_ATTENUATION_IGNORE_AIR_G_TYPE = 2717;
	JEOKDCIGCFP_BEYOND_VELOCITY_FORCE_TYPE_BEYOND_TYPE = 2718;
	JEOKDCIGCFP_BEYOND_VELOCITY_FORCE_TYPE_BEYOND_FORCE_FIELD_TYPE = 2719;
	JEOKDCIGCFP_BEYOND_VELOCITY_FORCE_TYPE_BEYOND_EJECT_TYPE = 2720;
	JEOKDCIGCFP_BEYOND_VELOCITY_FORCE_TYPE_BEYOND_DRAG_TYPE = 2721;
	JEOKDCIGCFP_BEYOND_CUSTOM_SKILL_MOVE_TYPE_COMBAT_SKILL_MOVE = 2800;
	JEOKDCIGCFP_BEYOND_CUSTOM_SKILL_MOVE_TYPE_COMBAT_AIR = 2801;
	JEOKDCIGCFP_BEYOND_CUSTOM_SKILL_SLOT_VISIBLE_TYPE_SHOW = 2802;
	JEOKDCIGCFP_BEYOND_CUSTOM_SKILL_SLOT_VISIBLE_TYPE_HIDE = 2803;
	JEOKDCIGCFP_BEYOND_CUSTOM_SKILL_INTERVAL_MODE_CLOSED = 2804;
	JEOKDCIGCFP_BEYOND_CUSTOM_SKILL_INTERVAL_MODE_OPEN = 2805;
	JEOKDCIGCFP_BEYOND_CUSTOM_SKILL_INTERVAL_MODE_OPEN_CLOSED = 2806;
	JEOKDCIGCFP_BEYOND_CUSTOM_SKILL_INTERVAL_MODE_CLOSED_OPEN = 2807;
	JEOKDCIGCFP_BEYOND_CUSTOM_SKILL_SLOT_STACK_TOP_HANDLE_TYPE_DESTROY = 2810;
	JEOKDCIGCFP_BEYOND_CUSTOM_SKILL_SLOT_STACK_TOP_HANDLE_TYPE_KEEP = 2811;
	JEOKDCIGCFP_BEYOND_CUSTOM_SKILL_SLOT_STACK_TOP_HANDLE_TYPE_UNBIND = 2812;
	JEOKDCIGCFP_BEYOND_CUSTOM_SKILL_SLOT_DUTY_CHANGE_HANDLE_TYPE_DESTROY = 2820;
	JEOKDCIGCFP_BEYOND_CUSTOM_SKILL_SLOT_DUTY_CHANGE_HANDLE_TYPE_KEEP = 2821;
	JEOKDCIGCFP_BEYOND_TURNMODE_PREFER_TARGET_TO_INPUT = 2900;
	JEOKDCIGCFP_BEYOND_TURNMODE_ONLY_INPUT = 2901;
	JEOKDCIGCFP_BEYOND_TURNMODE_ONLY_TARGET = 2902;
	JEOKDCIGCFP_BEYOND_TURNMODE_PREFER_TARGET_TO_CAMERA = 2903;
	JEOKDCIGCFP_BEYOND_TURNMODE_ONLY_CAMERA = 2904;
	JEOKDCIGCFP_BEYOND_TURNMODE_PREFER_INPUT_TO_TARGET = 2905;
	JEOKDCIGCFP_BEYOND_BORN_TYPE_SELF = 3000;
	JEOKDCIGCFP_BEYOND_BORN_TYPE_BORN_BY_COLLISION_POINT = 3001;
	JEOKDCIGCFP_BEYOND_CUSTOM_SKILL_SLOT_TYPE_ATTACK = 3100;
	JEOKDCIGCFP_BEYOND_CUSTOM_SKILL_SLOT_TYPE_SKILL1 = 3101;
	JEOKDCIGCFP_BEYOND_CUSTOM_SKILL_SLOT_TYPE_SKILL2 = 3102;
	JEOKDCIGCFP_BEYOND_CUSTOM_SKILL_SLOT_TYPE_SKILL3 = 3103;
	JEOKDCIGCFP_BEYOND_CUSTOM_SKILL_SLOT_TYPE_SKILL4 = 3104;
	JEOKDCIGCFP_BEYOND_CUSTOM_SKILL_SLOT_TYPE_SKILL11 = 3111;
	JEOKDCIGCFP_BEYOND_CUSTOM_SKILL_SLOT_TYPE_SKILL12 = 3112;
	JEOKDCIGCFP_BEYOND_CUSTOM_SKILL_SLOT_TYPE_SKILL13 = 3113;
	JEOKDCIGCFP_BEYOND_CUSTOM_SKILL_SLOT_TYPE_SKILL14 = 3114;
	JEOKDCIGCFP_BEYOND_CUSTOM_SKILL_SLOT_TYPE_SKILL21 = 3121;
	JEOKDCIGCFP_BEYOND_CUSTOM_SKILL_SLOT_TYPE_SKILL22 = 3122;
	JEOKDCIGCFP_BEYOND_CUSTOM_SKILL_SLOT_TYPE_SKILL23 = 3123;
	JEOKDCIGCFP_BEYOND_CUSTOM_SKILL_SLOT_TYPE_SKILL24 = 3124;
	JEOKDCIGCFP_BEYOND_CUSTOM_SKILL_SLOT_TYPE_SKILL25 = 3125;
	JEOKDCIGCFP_BEYOND_CUSTOM_SKILL_SLOT_TYPE_SKILL26 = 3126;
	JEOKDCIGCFP_BEYOND_CUSTOM_SKILL_SLOT_TYPE_SKILL27 = 3127;
	JEOKDCIGCFP_BEYOND_CUSTOM_SKILL_SLOT_TYPE_SKILL28 = 3128;
	JEOKDCIGCFP_BEYOND_CUSTOM_SKILL_SLOT_TYPE_SKILL29 = 3129;
	JEOKDCIGCFP_BEYOND_CUSTOM_SKILL_SLOT_TYPE_SKILL30 = 3130;
	JEOKDCIGCFP_BEYOND_CUSTOM_SKILL_SLOT_TYPE_SKILL31 = 3131;
	JEOKDCIGCFP_BEYOND_CUSTOM_SKILL_SLOT_TYPE_SKILL32 = 3132;
	JEOKDCIGCFP_BEYOND_CUSTOM_SKILL_SLOT_TYPE_SKILL33 = 3133;
	JEOKDCIGCFP_BEYOND_CUSTOM_SKILL_SLOT_TYPE_SKILL34 = 3134;
	JEOKDCIGCFP_BEYOND_CUSTOM_SKILL_SLOT_TYPE_SKILL35 = 3135;
	JEOKDCIGCFP_BEYOND_ENMITY_TRACE_TYPE_SELF = 3200;
	JEOKDCIGCFP_BEYOND_ENMITY_TRACE_TYPE_OWNER = 3201;
	JEOKDCIGCFP_BEYOND_ENMITY_TRACE_TYPE_TOP_OWNER = 3202;
	JEOKDCIGCFP_BEYOND_AI_THREAT_LEVEL_UNAWARE = 3300;
	JEOKDCIGCFP_BEYOND_AI_THREAT_LEVEL_AWARE = 3301;
	JEOKDCIGCFP_BEYOND_AI_THREAT_LEVEL_ALERT = 3302;
	JEOKDCIGCFP_BEYOND_ATTENUATION_CURVE_TYPE_LINEAR = 3400;
	JEOKDCIGCFP_BEYOND_ATTENUATION_CURVE_TYPE_EASE_OUT = 3401;
	JEOKDCIGCFP_BEYOND_ATTENUATION_CURVE_TYPE_EASE_IN = 3402;
	JEOKDCIGCFP_BEYOND_POP_UP_FINISH_TYPE_DEFAULT = 3500;
	JEOKDCIGCFP_BEYOND_POP_UP_FINISH_TYPE_TIME_OUT = 3501;
	JEOKDCIGCFP_BEYOND_POP_UP_FINISH_TYPE_REFRESH_ACT = 3502;
	JEOKDCIGCFP_BEYOND_POP_UP_FINISH_TYPE_REFRESH_ALL = 3503;
	JEOKDCIGCFP_BEYOND_POP_UP_FINISH_TYPE_CLOSE_ACT = 3504;
	JEOKDCIGCFP_BEYOND_POP_UP_FINISH_TYPE_CLOSE_BP = 3505;
	JEOKDCIGCFP_BEYOND_POP_UP_REFRESH_TYPE_NONE = 3510;
	JEOKDCIGCFP_BEYOND_POP_UP_REFRESH_TYPE_PART = 3511;
	JEOKDCIGCFP_BEYOND_POP_UP_REFRESH_TYPE_ALL = 3512;
	JEOKDCIGCFP_BEYOND_MONSTER_PATROL_SPEED_LEVEL_TYPE_IDLE = 3600;
	JEOKDCIGCFP_BEYOND_MONSTER_PATROL_SPEED_LEVEL_TYPE_WALK = 3601;
	JEOKDCIGCFP_BEYOND_MONSTER_PATROL_SPEED_LEVEL_TYPE_RUN = 3602;
	JEOKDCIGCFP_BEYOND_MONSTER_PATROL_SPEED_LEVEL_TYPE_SPRINT = 3603;
	JEOKDCIGCFP_BEYOND_MONSTER_PATROL_ROUTE_POINT_TYPE_NORMAL_MOVE = 3700;
	JEOKDCIGCFP_BEYOND_MONSTER_PATROL_ROUTE_POINT_TYPE_MOVE_AFTER_ROT = 3701;
	JEOKDCIGCFP_BEYOND_MONSTER_PATROL_MOVE_TYPE_ONCE = 3800;
	JEOKDCIGCFP_BEYOND_MONSTER_PATROL_MOVE_TYPE_ROUND = 3801;
	JEOKDCIGCFP_BEYOND_MONSTER_PATROL_MOVE_TYPE_LOOP = 3802;
	JEOKDCIGCFP_BEYOND_HIT_LEVEL_TYPE_MUTE = 3900;
	JEOKDCIGCFP_BEYOND_HIT_LEVEL_TYPE_SHAKE = 3901;
	JEOKDCIGCFP_BEYOND_HIT_LEVEL_TYPE_LIGHT = 3902;
	JEOKDCIGCFP_BEYOND_HIT_LEVEL_TYPE_HEAVY = 3903;
	JEOKDCIGCFP_BEYOND_HIT_LEVEL_TYPE_AIR = 3904;
	JEOKDCIGCFP_BEYOND_ATTACK_DAMAGE_ATTENUATION_DISTANCE_TYPE_BORN_POS = 4000;
	JEOKDCIGCFP_BEYOND_ATTACK_DAMAGE_ATTENUATION_DISTANCE_TYPE_CUR_POS = 4001;
	JEOKDCIGCFP_BEYOND_SETTLE_STATUS_NONE = 4100;
	JEOKDCIGCFP_BEYOND_SETTLE_STATUS_SUCC = 4101;
	JEOKDCIGCFP_BEYOND_SETTLE_STATUS_FAIL = 4102;
	JEOKDCIGCFP_BEYOND_SETTLE_STATUS_ESCAPE = 4103;
	JEOKDCIGCFP_BEYOND_STUFF_RARITY_WHITE = 4200;
	JEOKDCIGCFP_BEYOND_STUFF_RARITY_GREEN = 4201;
	JEOKDCIGCFP_BEYOND_STUFF_RARITY_BLUE = 4202;
	JEOKDCIGCFP_BEYOND_STUFF_RARITY_PURPLE = 4203;
	JEOKDCIGCFP_BEYOND_STUFF_RARITY_ORANGE = 4204;
	JEOKDCIGCFP_BEYOND_STUFF_CATEGORY_EQUIP = 4300;
	JEOKDCIGCFP_BEYOND_STUFF_CATEGORY_MATERIAL = 4301;
	JEOKDCIGCFP_BEYOND_STUFF_CATEGORY_CONSUMABLE = 4302;
	JEOKDCIGCFP_BEYOND_STUFF_CATEGORY_PRECIOUS = 4303;
	JEOKDCIGCFP_BEYOND_DROP_STUFF_OUTPUT_TYPE_SHARE = 4350;
	JEOKDCIGCFP_BEYOND_DROP_STUFF_OUTPUT_TYPE_INDEPENDENT = 4351;
	JEOKDCIGCFP_BEYOND_BASE_PROP_TYPE_HP = 4400;
	JEOKDCIGCFP_BEYOND_BASE_PROP_TYPE_HP_PERCENT = 4401;
	JEOKDCIGCFP_BEYOND_BASE_PROP_TYPE_ATTACK = 4402;
	JEOKDCIGCFP_BEYOND_BASE_PROP_TYPE_ATTACK_PERCENT = 4403;
	JEOKDCIGCFP_BEYOND_BASE_PROP_TYPE_DEFENSE = 4404;
	JEOKDCIGCFP_BEYOND_BASE_PROP_TYPE_DEFENSE_PERCENT = 4405;
	JEOKDCIGCFP_BEYOND_BASE_PROP_TYPE_FIRE_SUB_HURT = 4406;
	JEOKDCIGCFP_BEYOND_BASE_PROP_TYPE_ELEC_SUB_HURT = 4407;
	JEOKDCIGCFP_BEYOND_BASE_PROP_TYPE_WATER_SUB_HURT = 4408;
	JEOKDCIGCFP_BEYOND_BASE_PROP_TYPE_GRASS_SUB_HURT = 4409;
	JEOKDCIGCFP_BEYOND_BASE_PROP_TYPE_WIND_SUB_HURT = 4410;
	JEOKDCIGCFP_BEYOND_BASE_PROP_TYPE_ROCK_SUB_HURT = 4411;
	JEOKDCIGCFP_BEYOND_BASE_PROP_TYPE_ICE_SUB_HURT = 4412;
	JEOKDCIGCFP_BEYOND_BASE_PROP_TYPE_CRITICAL = 4413;
	JEOKDCIGCFP_BEYOND_BASE_PROP_TYPE_CRITICAL_HURT = 4414;
	JEOKDCIGCFP_BEYOND_BASE_PROP_TYPE_HEAL_ADD = 4415;
	JEOKDCIGCFP_BEYOND_BASE_PROP_TYPE_HEALED_ADD = 4416;
	JEOKDCIGCFP_BEYOND_BASE_PROP_TYPE_FIRE_ADD_HURT = 4417;
	JEOKDCIGCFP_BEYOND_BASE_PROP_TYPE_ELEC_ADD_HURT = 4418;
	JEOKDCIGCFP_BEYOND_BASE_PROP_TYPE_WATER_ADD_HURT = 4419;
	JEOKDCIGCFP_BEYOND_BASE_PROP_TYPE_GRASS_ADD_HURT = 4420;
	JEOKDCIGCFP_BEYOND_BASE_PROP_TYPE_WIND_ADD_HURT = 4421;
	JEOKDCIGCFP_BEYOND_BASE_PROP_TYPE_ROCK_ADD_HURT = 4422;
	JEOKDCIGCFP_BEYOND_BASE_PROP_TYPE_ICE_ADD_HURT = 4423;
	JEOKDCIGCFP_BEYOND_BASE_PROP_TYPE_PHYSICAL_ADD_HURT = 4424;
	JEOKDCIGCFP_BEYOND_ELEMENT_REACTION_TYPE_NONE = 4700;
	JEOKDCIGCFP_BEYOND_ELEMENT_REACTION_TYPE_EXPLODE = 4701;
	JEOKDCIGCFP_BEYOND_ELEMENT_REACTION_TYPE_STREAM = 4702;
	JEOKDCIGCFP_BEYOND_ELEMENT_REACTION_TYPE_BURNING = 4703;
	JEOKDCIGCFP_BEYOND_ELEMENT_REACTION_TYPE_BURNED = 4704;
	JEOKDCIGCFP_BEYOND_ELEMENT_REACTION_TYPE_WET = 4705;
	JEOKDCIGCFP_BEYOND_ELEMENT_REACTION_TYPE_OVERGROW = 4706;
	JEOKDCIGCFP_BEYOND_ELEMENT_REACTION_TYPE_MELT = 4707;
	JEOKDCIGCFP_BEYOND_ELEMENT_REACTION_TYPE_FREEZE = 4708;
	JEOKDCIGCFP_BEYOND_ELEMENT_REACTION_TYPE_ANTI_FIRE = 4709;
	JEOKDCIGCFP_BEYOND_ELEMENT_REACTION_TYPE_ROCK = 4710;
	JEOKDCIGCFP_BEYOND_ELEMENT_REACTION_TYPE_SLOW_DOWN = 4711;
	JEOKDCIGCFP_BEYOND_ELEMENT_REACTION_TYPE_SHOCK = 4712;
	JEOKDCIGCFP_BEYOND_ELEMENT_REACTION_TYPE_WIND = 4713;
	JEOKDCIGCFP_BEYOND_ELEMENT_REACTION_TYPE_ELECTRIC = 4714;
	JEOKDCIGCFP_BEYOND_ELEMENT_REACTION_TYPE_FIRE = 4715;
	JEOKDCIGCFP_BEYOND_ELEMENT_REACTION_TYPE_SUPERCONDUCTOR = 4716;
	JEOKDCIGCFP_BEYOND_ELEMENT_REACTION_TYPE_SWIRL_FIRE = 4717;
	JEOKDCIGCFP_BEYOND_ELEMENT_REACTION_TYPE_SWIRL_WATER = 4718;
	JEOKDCIGCFP_BEYOND_ELEMENT_REACTION_TYPE_SWIRL_ELECTRIC = 4719;
	JEOKDCIGCFP_BEYOND_ELEMENT_REACTION_TYPE_SWIRL_ICE = 4720;
	JEOKDCIGCFP_BEYOND_ELEMENT_REACTION_TYPE_SWIRL_FIRE_ACCUMULATE = 4721;
	JEOKDCIGCFP_BEYOND_ELEMENT_REACTION_TYPE_SWIRL_WATER_ACCUMULATE = 4722;
	JEOKDCIGCFP_BEYOND_ELEMENT_REACTION_TYPE_SWIRL_ELECTRIC_ACCUMULATE = 4723;
	JEOKDCIGCFP_BEYOND_ELEMENT_REACTION_TYPE_SWIRL_ICE_ACCUMULATE = 4724;
	JEOKDCIGCFP_BEYOND_ELEMENT_REACTION_TYPE_STICK_ROCK = 4725;
	JEOKDCIGCFP_BEYOND_ELEMENT_REACTION_TYPE_STICK_WATER = 4726;
	JEOKDCIGCFP_BEYOND_ELEMENT_REACTION_TYPE_CRYSTALLIZE_FIRE = 4727;
	JEOKDCIGCFP_BEYOND_ELEMENT_REACTION_TYPE_CRYSTALLIZE_WATER = 4728;
	JEOKDCIGCFP_BEYOND_ELEMENT_REACTION_TYPE_CRYSTALLIZE_ELECTRIC = 4729;
	JEOKDCIGCFP_BEYOND_ELEMENT_REACTION_TYPE_CRYSTALLIZE_ICE = 4730;
	JEOKDCIGCFP_BEYOND_ELEMENT_REACTION_TYPE_FROZEN_BROKEN = 4731;
	JEOKDCIGCFP_BEYOND_ELEMENT_REACTION_TYPE_STICK_GRASS = 4732;
	JEOKDCIGCFP_BEYOND_ELEMENT_REACTION_TYPE_OVERDOSE = 4733;
	JEOKDCIGCFP_BEYOND_ELEMENT_REACTION_TYPE_OVERDOSE_ELECTRIC = 4734;
	JEOKDCIGCFP_BEYOND_ELEMENT_REACTION_TYPE_OVERDOSE_GRASS = 4735;
	JEOKDCIGCFP_BEYOND_ELEMENT_REACTION_TYPE_OVERGROW_MUSHROOM_FIRE = 4736;
	JEOKDCIGCFP_BEYOND_ELEMENT_REACTION_TYPE_OVERGROW_MUSHROOM_ELECTRIC = 4737;
	JEOKDCIGCFP_BEYOND_ELEMENT_REACTION_TYPE_PHLOGISTON_SOLIDIFICATION = 4738;
	JEOKDCIGCFP_BEYOND_ELEMENT_REACTION_TYPE_PHLOGISTON_SOLIDIFICATION_END = 4739;
	JEOKDCIGCFP_BEYOND_ELEMENT_REACTION_TYPE_MOON_SHOCK = 4740;
	JEOKDCIGCFP_BEYOND_ELEMENT_REACTION_TYPE_MOON_OVERGROW = 4741;
	JEOKDCIGCFP_BEYOND_ELEMENT_REACTION_TYPE_MOON_CRYSTALLIZE_WATER = 4742;
	JEOKDCIGCFP_BEYOND_ELEMENT_REACTION_TYPE_STAR_SUPERCONDUCTOR = 4743;
	JEOKDCIGCFP_BEYOND_ELEMENT_REACTION_TYPE_STAR_SWIRL_ICE = 4744;
	JEOKDCIGCFP_BEYOND_BAG_STUFF_CHANGE_ACTION_DESTROY = 4900;
	JEOKDCIGCFP_BEYOND_BAG_STUFF_CHANGE_ACTION_DROP = 4901;
	JEOKDCIGCFP_BEYOND_BAG_STUFF_CHANGE_ACTION_USE = 4902;
	JEOKDCIGCFP_BEYOND_BAG_STUFF_CHANGE_ACTION_DIE_DROP = 4903;
	JEOKDCIGCFP_BEYOND_BAG_STUFF_CHANGE_ACTION_SHOP_TRADE = 4904;
	JEOKDCIGCFP_BEYOND_BAG_STUFF_CHANGE_ACTION_BLUEPRINT_OPERATION = 4905;
	JEOKDCIGCFP_BEYOND_BAG_STUFF_CHANGE_ACTION_PICK_UP = 4950;
	JEOKDCIGCFP_BEYOND_SCAN_ENTITY_STATE_NONE = 5000;
	JEOKDCIGCFP_BEYOND_SCAN_ENTITY_STATE_AVAILABLE_TARGET = 5001;
	JEOKDCIGCFP_BEYOND_SCAN_ENTITY_STATE_AVAILABLE_NOT_TARGET = 5002;
	JEOKDCIGCFP_BEYOND_SCAN_ENTITY_STATE_NOT_AVAILABLE = 5003;
	JEOKDCIGCFP_BEYOND_SCAN_ENTITY_SCORE_RULE_TYPE_VIEW = 5100;
	JEOKDCIGCFP_BEYOND_SCAN_ENTITY_SCORE_RULE_TYPE_DISTANCE = 5101;
	JEOKDCIGCFP_BEYOND_ENDURE_STATE_TYPE_NORMAL = 5200;
	JEOKDCIGCFP_BEYOND_ENDURE_STATE_TYPE_RECOVER = 5201;
	JEOKDCIGCFP_BEYOND_ENDURE_STATE_TYPE_PROTECT = 5202;
	JEOKDCIGCFP_BEYOND_CHAT_CHANNEL_TYPE_ARMY = 5300;
	JEOKDCIGCFP_BEYOND_CHAT_CHANNEL_TYPE_CUSTOM_PLAYER = 5301;
	JEOKDCIGCFP_BEYOND_ABILITY_SHOW_DAMAGE_TEXT_TYPE_NONE = 5400;
	JEOKDCIGCFP_BEYOND_ABILITY_SHOW_DAMAGE_TEXT_TYPE_NORMAL = 5401;
	JEOKDCIGCFP_BEYOND_ABILITY_SHOW_DAMAGE_TEXT_TYPE_CRITICAL = 5402;
	JEOKDCIGCFP_BEYOND_FIXED_POS_ROT_MOVER_MOVE_TYPE_IMMEDIATE = 5500;
	JEOKDCIGCFP_BEYOND_FIXED_POS_ROT_MOVER_MOVE_TYPE_UNIFORM_LINEAR = 5501;
	JEOKDCIGCFP_BEYOND_FIXED_POS_ROT_MOVER_PARAM_TRANS_TYPE_SPEED_BASE = 5600;
	JEOKDCIGCFP_BEYOND_FIXED_POS_ROT_MOVER_PARAM_TRANS_TYPE_TIME_BASE = 5601;
	JEOKDCIGCFP_BEYOND_PLAY_TYPE_TRIAL = 5700;
	JEOKDCIGCFP_BEYOND_PLAY_TYPE_ROOM = 5701;
	JEOKDCIGCFP_BEYOND_PLAY_TYPE_MATCH = 5702;
	JEOKDCIGCFP_BEYOND_PLAYER_INPUT_DEVICE_TYPE_KEYBOARD = 5800;
	JEOKDCIGCFP_BEYOND_PLAYER_INPUT_DEVICE_TYPE_CONTROLLER = 5801;
	JEOKDCIGCFP_BEYOND_PLAYER_INPUT_DEVICE_TYPE_TOUCH_SCREEN = 5802;
	JEOKDCIGCFP_BEYOND_MONSTER_VERSION_TYPE_MONSTER_V1 = 5900;
	JEOKDCIGCFP_BEYOND_MONSTER_VERSION_TYPE_MONSTER_V2 = 5901;
	JEOKDCIGCFP_BEYOND_CLIENT_AI_TARGET_TYPE_THREAT = 6000;
	JEOKDCIGCFP_BEYOND_CLIENT_AI_TARGET_TYPE_OWNER = 6001;
	JEOKDCIGCFP_BEYOND_CLIENT_AI_TARGET_TYPE_CHILDREN = 6002;
	JEOKDCIGCFP_BEYOND_CLIENT_AI_TARGET_TYPE_SELF = 6003;
	JEOKDCIGCFP_BEYOND_CLIENT_AI_TARGET_TYPE_TARGET = 6004;
	JEOKDCIGCFP_BEYOND_CLIENT_AI_TARGET_TYPE_TARGET_TEAM = 6005;
	JEOKDCIGCFP_BEYOND_CLIENT_AI_TARGET_TYPE_COMMAND = 6006;
	JEOKDCIGCFP_BEYOND_CLIENT_AI_TARGET_TYPE_LEVEL_ENTITY = 6007;
	JEOKDCIGCFP_BEYOND_CLIENT_AI_TACTIC_ROTATE_DIR_TYPE_DEFAULT = 6100;
	JEOKDCIGCFP_BEYOND_CLIENT_AI_TACTIC_ROTATE_DIR_TYPE_CLOCKWISE = 6101;
	JEOKDCIGCFP_BEYOND_CLIENT_AI_TACTIC_ROTATE_DIR_TYPE_ANTICLOCKWISE = 6102;
	JEOKDCIGCFP_BEYOND_CLIENT_AI_TACTIC_TYPE_IDLE = 6200;
	JEOKDCIGCFP_BEYOND_CLIENT_AI_TACTIC_TYPE_MOVE_TO_MANUAL_POSITION = 6201;
	JEOKDCIGCFP_BEYOND_CLIENT_AI_TACTIC_TYPE_MOVE_TO_MANUAL_TARGET = 6202;
	JEOKDCIGCFP_BEYOND_CLIENT_AI_TACTIC_TYPE_ROTATE_TO_MANUAL_ROTATION = 6203;
	JEOKDCIGCFP_BEYOND_CLIENT_AI_TACTIC_TYPE_ROTATE_MANUAL_ANGLE = 6204;
	JEOKDCIGCFP_BEYOND_CLIENT_AI_TACTIC_TYPE_MELEE_CHARGE = 6205;
	JEOKDCIGCFP_BEYOND_CLIENT_AI_TACTIC_TYPE_FLEE = 6206;
	JEOKDCIGCFP_BEYOND_CLIENT_AI_TACTIC_TYPE_WANDER = 6207;
	JEOKDCIGCFP_BEYOND_CLIENT_AI_TACTIC_TYPE_RETURN_TO_BORN = 6208;
	JEOKDCIGCFP_BEYOND_CLIENT_AI_TACTIC_TYPE_FACING_MOVE = 6209;
	JEOKDCIGCFP_BEYOND_CLIENT_AI_TACTIC_TYPE_FOLLOW_SERVER_ROUTE = 6210;
	JEOKDCIGCFP_BEYOND_CLIENT_AI_TACTIC_TYPE_ROTATE_TO_MANUAL_TARGET = 6211;
	JEOKDCIGCFP_BEYOND_BOOL_TYPE_FALSE = 6300;
	JEOKDCIGCFP_BEYOND_BOOL_TYPE_TRUE = 6301;
	JEOKDCIGCFP_BEYOND_MODEL_COLOR_MATERIAL_BLEND_OVERRIDE = 6700;
	JEOKDCIGCFP_BEYOND_MODEL_COLOR_MATERIAL_BLEND_MULTIPLY = 6701;
	JEOKDCIGCFP_BEYOND_MODEL_COLOR_MATERIAL_FILL_ICE = 6710;
	JEOKDCIGCFP_BEYOND_MODEL_COLOR_MATERIAL_FILL_PETRIFIED = 6711;
	JEOKDCIGCFP_BEYOND_MODEL_COLOR_MATERIAL_FILL_GRID_LINES = 6712;
	JEOKDCIGCFP_BEYOND_MODEL_COLOR_MATERIAL_FILL_TRANSLUCENT = 6713;
	JEOKDCIGCFP_BEYOND_PRE_TARGET_END_REASON_NONE = 6800;
	JEOKDCIGCFP_BEYOND_PRE_TARGET_END_REASON_FINISH = 6801;
	JEOKDCIGCFP_BEYOND_PRE_TARGET_END_REASON_CANCEL = 6802;
	JEOKDCIGCFP_BEYOND_CLIENT_TARGET_SORT_TYPE_DEFAULT = 1000001;
	JEOKDCIGCFP_BEYOND_CLIENT_TARGET_SORT_TYPE_RANDOM = 1000002;
	JEOKDCIGCFP_BEYOND_CLIENT_TARGET_SORT_TYPE_NEAREST = 1000003;
	JEOKDCIGCFP_BEYOND_CLIENT_FILTER_TYPE_BOOL = 1000010;
	JEOKDCIGCFP_BEYOND_CLIENT_FILTER_TYPE_INT = 10000011;
}
