syntax = "proto3";

option java_package = "emu.grasscutter.net.proto";
option java_outer_classname = "PKEOGNLGCPJOuterClass";

enum PKEOGNLGCPJ {
	PKEOGNLGCPJ_NONE = 0;
	PKEOGNLGCPJ_DESTORY_VEHCILE = 1;
	PKEOGNLGCPJ_ENTER_SCENE = 2;
	PKEOGNLGCPJ_LEAVE_SCENE = 3;
	PKEOGNLGCPJ_ACTIVE_VEHCILE = 4;
	PKEOGNLGCPJ_ENTER_VEHICLE = 5;
	PKEOGNLGCPJ_SPEED_CHECK = 6;
	PKEOGNLGCPJ_GM = 7;
	PKEOGNLGCPJ_USE_WIDGET_TP = 8;
	PKEOGNLGCPJ_USE_WIDGET_NOT_TP = 9;
	PKEOGNLGCPJ_GALLERY_VEHCILE_NOT_TP = 10;
	PKEOGNLGCPJ_QUEST_EXEC = 11;
}
