syntax = "proto3";

option java_package = "emu.grasscutter.net.proto";
option java_outer_classname = "TrialAvatarActivityRewardDetailInfoOuterClass";

message TrialAvatarActivityRewardDetailInfo {
	repeated uint32 _passed_training_step_list = 1;
	bool _is_avatar_owned = 3;
	uint32 reward_id = 4;
	bool passed_dungeon = 5;
	bool received_reward = 9;
	bool is_can_take_reward = 10;
	repeated uint32 _available_training_step_list = 12;
	uint32 trial_avatar_index_id = 13;
	bool _is_skip_training = 14;
}
